/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/
import { GoogleGenAI, GenerateContentResponse } from "@google/genai";

// Using gemini-3.1-flash-image-preview for high-quality 2D realistic rendering.
const GEMINI_MODEL = 'gemini-3.1-flash-image-preview';

const SYSTEM_INSTRUCTION = `You are an expert Architectural Visualizer and CGI Artist specializing in "CAD to Realistic Rendering" transformations.
Your goal is to take a primary 2D CAD drawing (floor plan, section, or elevation) and a set of "Mood Board" inspiration images, and generate a single, highly realistic 2D interior or exterior rendering.

CORE DIRECTIVES:
1. **Spatial Fidelity**: Respect the geometry and layout of the primary CAD drawing. Do not invent walls or structural elements that aren't there.
2. **Material & Style Transfer**: Analyze the mood board images for textures, materials (wood, stone, fabric), color palettes, and lighting styles. Apply these to the CAD layout.
3. **Photorealism**: The output must look like a professional architectural photograph. Pay close attention to light bounces, shadows, reflections, and depth of field.
4. **Atmosphere**: Capture the "vibe" of the mood board—whether it's minimalist, brutalist, cozy, or industrial.

INPUT STRUCTURE:
- The first image provided is ALWAYS the primary CAD drawing.
- Subsequent images are Mood Board inspiration.

OUTPUT:
- You must generate a single, high-quality image that represents the final rendering with respect to the CAD layout and mood board inspiration.`;

export interface InputImage {
  data: string; // base64
  mimeType: string;
}

export async function renderVision(
  cadImage: InputImage,
  moodBoardImages: InputImage[],
  prompt?: string
): Promise<string> {
  // Initialize inside the function to ensure the latest API key is used
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    throw new Error("GEMINI_API_KEY is not defined in the environment.");
  }
  const ai = new GoogleGenAI({ apiKey });

  const parts: any[] = [];
  
  // Add the primary CAD drawing
  parts.push({
    inlineData: cadImage
  });

  // Add mood board images
  moodBoardImages.forEach(img => {
    parts.push({
      inlineData: img
    });
  });

  // Add text instructions
  const finalPrompt = `
    PRIMARY TASK: Generate a realistic 2D architectural rendering based on the first image (CAD drawing) provided.
    STYLE INFLUENCE: Use the subsequent images as a mood board for materials, colors, and lighting.
    ADDITIONAL NOTES: ${prompt || "Create a professional, photorealistic interior rendering while maintaining the integrity of the CAD layout and mood board inspiration."}
    
    Ensure the final output is a single image part.
  `;
  parts.push({ text: finalPrompt });

  try {
    const response: GenerateContentResponse = await ai.models.generateContent({
      model: GEMINI_MODEL,
      contents: {
        parts: parts
      },
      config: {
        systemInstruction: SYSTEM_INSTRUCTION,
        imageConfig: {
          aspectRatio: "16:9",
          imageSize: "1K"
        }
      },
    });

    // Find the image part in the response
    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
      }
    }

    throw new Error("No image was generated by the model.");
  } catch (error) {
    console.error("Gemini Rendering Error:", error);
    throw error;
  }
}

export async function refineVision(
  renderedImage: InputImage,
  refinementPrompt: string,
  contextImages: InputImage[] = []
): Promise<string> {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    throw new Error("GEMINI_API_KEY is not defined in the environment.");
  }

  const ai = new GoogleGenAI({ apiKey });
  const parts: any[] = [];

  parts.push({
    inlineData: renderedImage,
  });

  contextImages.forEach((img) => {
    parts.push({
      inlineData: img,
    });
  });

  parts.push({
    text: `
      PRIMARY TASK: Refine the first image with subtle edits based on user instructions.
      IMPORTANT: Preserve the existing composition, camera angle, and architectural structure unless explicitly requested otherwise.
      REFINE INSTRUCTIONS: ${refinementPrompt}

      Return one high-quality final image only.
    `,
  });

  try {
    const response: GenerateContentResponse = await ai.models.generateContent({
      model: GEMINI_MODEL,
      contents: {
        parts,
      },
      config: {
        systemInstruction: SYSTEM_INSTRUCTION,
        imageConfig: {
          aspectRatio: "16:9",
          imageSize: "1K",
        },
      },
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
      }
    }

    throw new Error("No refined image was generated by the model.");
  } catch (error) {
    console.error("Gemini Refinement Error:", error);
    throw error;
  }
}
