/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/

export interface InputImage {
  data: string; // base64
  mimeType: string;
}

// Ensure proper URL depending on DEV or PROD
const BACKEND_URL = import.meta.env.VITE_BACKEND_URL || '';

export async function renderVision(
  cadImage: InputImage,
  moodBoardImages: InputImage[],
  prompt?: string
): Promise<string> {
  const url = BACKEND_URL ? `${BACKEND_URL}/api/render` : `/api/render`;
  
  const response = await fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      cadImage,
      moodBoardImages,
      prompt
    })
  });

  if (!response.ok) {
    const errorData = await response.json().catch(() => ({}));
    throw new Error(errorData.error || `HTTP error! status: ${response.status}`);
  }

  const data = await response.json();
  if (!data?.result) {
    throw new Error("No image was generated by the backend.");
  }
  return data.result;
}

export async function refineVision(
  renderedImage: InputImage,
  refinementPrompt: string,
  contextImages: InputImage[] = []
): Promise<string> {
  const url = BACKEND_URL ? `${BACKEND_URL}/api/refine` : `/api/refine`;
  const response = await fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({ renderedImage, refinementPrompt, contextImages })
  });

  if (!response.ok) {
    const err = await response.json().catch(() => ({}));
    throw new Error(err.error || "Failed to refine vision");
  }
  
  const data = await response.json();
  return data.result;
}
