import path from "path";
import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import rateLimit from 'express-rate-limit';
import { GoogleGenAI, GenerateContentResponse } from '@google/genai';

dotenv.config({ path: __dirname + '/../../.env' }); // try root .env if running from src or dist
dotenv.config(); // fallback

const app = express();
const PORT = process.env.PORT || 5555;

// Middleware
app.use(cors());
app.use(express.json({ limit: '50mb' })); // High limit since we accept base64 images

// Rate Limiting
const apiLimiter = rateLimit({
  windowMs: 15 * 60 * 1000, // 15 minutes
  max: 100, // Limit each IP to 100 requests per `window` (here, per 15 minutes)
  message: 'Too many requests generated from this IP, please try again after 15 minutes',
  standardHeaders: true,
  legacyHeaders: false,
});

app.use('/api/', apiLimiter);

// ----------------------------------------------------------------------
// Gemini Setup & Configuration
// ----------------------------------------------------------------------
const GEMINI_MODEL = 'gemini-3.1-flash-image-preview';

const SYSTEM_INSTRUCTION = `You are an expert Architectural Visualizer and CGI Artist specializing in "CAD to Realistic Rendering" transformations.
Your goal is to take a primary 2D CAD drawing (floor plan, section, or elevation) and a set of "Mood Board" inspiration images, and generate a single, highly realistic 2D interior or exterior rendering.

CORE DIRECTIVES:
1. **Spatial Fidelity**: Respect the geometry and layout of the primary CAD drawing. Do not invent walls or structural elements that aren't there.
2. **Material & Style Transfer**: Analyze the mood board images for textures, materials (wood, stone, fabric), color palettes, and lighting styles. Apply these to the CAD layout.
3. **Photorealism**: The output must look like a professional architectural photograph. Pay close attention to light bounces, shadows, reflections, and depth of field.
4. **Atmosphere**: Capture the "vibe" of the mood board—whether it's minimalist, brutalist, cozy, or industrial.

INPUT STRUCTURE:
- The first image provided is ALWAYS the primary CAD drawing.
- Subsequent images are Mood Board inspiration.

OUTPUT:
- You must generate a single, high-quality image that represents the final rendering with respect to the CAD layout and mood board inspiration.`;

// Initialize GoogleGenAI
const apiKey = process.env.GEMINI_API_KEY;
if (!apiKey) {
  console.error('CRITICAL: GEMINI_API_KEY is not defined in the backend environment.');
}
const ai = new GoogleGenAI({ apiKey: apiKey || '' });

export interface InputImage {
  data: string; // base64
  mimeType: string;
}

// ----------------------------------------------------------------------
// Routes
// ----------------------------------------------------------------------
app.post('/api/render', async (req, res) => {
  try {
    const { cadImage, moodBoardImages, prompt } = req.body;

    if (!cadImage) {
      return res.status(400).json({ error: 'Missing cadImage parameter.' });
    }

    const parts: any[] = [];

    // Add the primary CAD drawing
    parts.push({
      inlineData: cadImage
    });

    // Add mood board images
    if (moodBoardImages && Array.isArray(moodBoardImages)) {
      moodBoardImages.forEach((img: InputImage) => {
        parts.push({ inlineData: img });
      });
    }

    // Add text instructions
    const finalPrompt = `
      PRIMARY TASK: Generate a realistic 2D architectural rendering based on the first image (CAD drawing) provided.
      STYLE INFLUENCE: Use the subsequent images as a mood board for materials, colors, and lighting.
      ADDITIONAL NOTES: ${prompt || "Create a professional, photorealistic interior rendering while maintaining the integrity of the CAD layout and mood board inspiration."}
      
      Ensure the final output is a single image part.
    `;
    parts.push({ text: finalPrompt });

    const response: GenerateContentResponse = await ai.models.generateContent({
      model: GEMINI_MODEL,
      contents: {
        parts: parts
      },
      config: {
        systemInstruction: SYSTEM_INSTRUCTION,
        imageConfig: {
          aspectRatio: "16:9",
          imageSize: "1K"
        }
      },
    });

    // Extract the generated image data
    let base64Output = null;
    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        base64Output = `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
        break;
      }
    }

    if (!base64Output) {
      throw new Error('No image was generated by the model.');
    }

    return res.json({ result: base64Output });
  } catch (error: any) {
    console.error('Gemini Rendering Error:', error);
    return res.status(500).json({ error: error.message || 'An error occurred during rendering.' });
  }
});

// Assuming a refine endpoint was stubbed out in the front end
app.post('/api/refine', async (req, res) => {
  try {
    const { renderedImage, refinementPrompt, contextImages } = req.body;

    if (!renderedImage || !refinementPrompt) {
      return res.status(400).json({ error: 'Missing renderedImage or refinementPrompt parameter.' });
    }

    const parts: any[] = [];

    // Add the image to refine
    parts.push({
      inlineData: renderedImage
    });

    // Add any context images
    if (contextImages && Array.isArray(contextImages)) {
      contextImages.forEach((img: InputImage) => {
        parts.push({ inlineData: img });
      });
    }

    // Add text instructions
    const finalPrompt = `
      PRIMARY TASK: Refine the provided architectural rendering based on the user's instructions.
      USER INSTRUCTIONS: ${refinementPrompt}
      
      Maintain the overall spatial layout and high-quality photorealism while adjusting elements as requested.
      Ensure the final output is a single image part.
    `;
    parts.push({ text: finalPrompt });

    const response: GenerateContentResponse = await ai.models.generateContent({
      model: GEMINI_MODEL,
      contents: {
        parts: parts
      },
      config: {
        systemInstruction: SYSTEM_INSTRUCTION,
        imageConfig: {
          aspectRatio: "16:9",
          imageSize: "1K"
        }
      },
    });

    // Extract the generated image data
    let base64Output = null;
    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        base64Output = `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
        break;
      }
    }

    if (!base64Output) {
      throw new Error('No image was generated by the model.');
    }

    return res.json({ result: base64Output });
  } catch (error: any) {
    console.error('Gemini Refinement Error:', error);
    return res.status(500).json({ error: error.message || 'An error occurred during refinement.' });
  }
});

// ----------------------------------------------------------------------
// Serve Static Frontend (Single Port Deployment)
// ----------------------------------------------------------------------
const frontendDistPath = path.join(__dirname, '../../dist');
app.use(express.static(frontendDistPath));

app.get('*', (req, res) => {
  res.sendFile(path.join(frontendDistPath, 'index.html'));
});

// Start Server
app.listen(PORT, () => {
  console.log(`Server is running on port ${PORT}`);
});